apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentmgr
  labels:
    app: studentmgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentmgr
  template:
    metadata:
      labels:
        app: studentmgr
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: studentmgr
          image: ghcr.io/thangdh2work/java-web-oop-workshop:84f16218611bbb96a823223396d2cb3090af1a02
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "mysql"
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "studentdb"
            - name: DB_USER
              value: "studentdb"
            - name: DB_PASSWORD
              value: "Sysp3xVbCom3cNEB4"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
