name: CD - update deployment image tag

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_run:
    workflows: ["CI"]
    types: ["completed"]

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure file exists
        run: |
          FILE="deploy/studentmgr/deployment.yaml"
          if [ ! -f "$FILE" ]; then
            echo "deployment.yaml not found"
            exit 1
          fi

      - name: Replace image tag in deployment.yaml
        env:
          TAG: ${{ github.event.inputs.image_tag }}
        run: |
          FILE="deploy/studentmgr/deployment.yaml"
          # Replace the tag portion of image: <repo>/<name>:<tag>
          # Pattern: image:  optional-spaces  non-colon-chars  :  current-tag
          sed -E -i "s#(image:[[:space:]]*[^:]+:)[^[:space:],]+#\1${TAG}#g" "$FILE"
          echo "Updated $FILE:"
          sed -n '1,200p' "$FILE"

      - name: Commit and push change
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FILE="deploy/studentmgr/deployment.yaml"
          if git status --porcelain | grep -q "$FILE"; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add "$FILE"
            git commit -m "chore(cd): update deployment image tag to ${{ github.event.inputs.image_tag }}"
            # set authenticated remote and push back to the current branch
            BRANCH="${GITHUB_REF#refs/heads/}"
            git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            git push origin "HEAD:${BRANCH}"
          else
            echo "No changes to commit."
          fi
