name: CI - build, test, coverage, image scan

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build & Test with Coverage (JaCoCo)
        run: |
          mvn -q -B -DskipTests dependency:go-offline
          mvn -q -B test
      - name: Archive coverage report (JaCoCo)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

  build-and-push-image:
    needs: build-test-coverage
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

  trivy-scan:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-fs.sarif"
          severity: "HIGH,CRITICAL"
      - name: Run Trivy Image scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: "ghcr.io/${{ github.repository }}:${{ github.sha }}"
          format: "sarif"
          output: "trivy-image.sarif"
          ignore-unfixed: true
          severity: "HIGH,CRITICAL"
      - name: Upload SARIF (Image)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
      - name: Upload SARIF (FS)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
